# Copyright (c) 2021-2026 Huawei Device Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Parse HarmonyOS/OpenHarmony kernel memory-leak artifacts."""

import argparse
import json
import re
import sys
import uuid
from collections import defaultdict
from copy import deepcopy
from pathlib import Path
from typing import Dict, List

import dill

from common.enum.common_enum import KernelMemoryReason
from log_manager.slicing.leak.memory_leak.common_log.kernel_header import KernelHeader
from log_manager.slicing.leak.memory_leak.common_log.mem_check_detial_info import MemCheckDetialInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_meminfo import MemCheckMemInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_proc_info import MemCheckProcInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_smaps_info import MemCheckSmapsInfo
from log_manager.slicing.leak.memory_leak.common_log.process_dma_buf_info import ProcessDmaBuf
from tools.file_tools import read_file_to_list
from tools.memleak_file_name import parse_kernel_file_name


REASON_ALIASES = {
    'ion': KernelMemoryReason.ION.value,
    'dma': KernelMemoryReason.ION.value,
    'dmabuf': KernelMemoryReason.ION.value,
    'dma_buf': KernelMemoryReason.ION.value,
    'dmaheap': KernelMemoryReason.ION.value,
    'dma_heap': KernelMemoryReason.ION.value,
    'dma-heap': KernelMemoryReason.ION.value,
    'ashmem': KernelMemoryReason.ASHMEM.value,
    'gpu': KernelMemoryReason.GPU.value,
    'slab': KernelMemoryReason.SLAB.value,
    'kernel_zone': KernelMemoryReason.KERNEL_ZONE.value,
    'kernelzone': KernelMemoryReason.KERNEL_ZONE.value,
}
DMA_MARKERS = {'MM_DMABUF_INFO', 'LOGGER_PROCESS_DMABUF_INFO'}


def _human_bytes(size: int) -> str:
    return f'{size} B ({size / 1024 / 1024:.2f} MiB)'


def _format_table(headers, rows) -> str:
    string_rows = [[str(value) for value in row] for row in rows]
    all_rows = [list(headers)] + string_rows
    widths = [max(len(row[index]) for row in all_rows) for index in range(len(headers))]
    lines = [
        ' | '.join(value.ljust(widths[index]) for index, value in enumerate(all_rows[0])),
        '-+-'.join('-' * width for width in widths),
    ]
    lines.extend(
        ' | '.join(value.ljust(widths[index]) for index, value in enumerate(row))
        for row in string_rows
    )
    return '\n'.join(lines)


def write_pickle_atomic(kernel_leak, output_path: Path):
    """Write a pickle without leaving a successful-looking partial result."""
    temporary_path = output_path.with_name(
        f'.{output_path.name}.{uuid.uuid4().hex}.tmp'
    )
    try:
        with temporary_path.open('wb') as file:
            dill.dump(kernel_leak, file)
        temporary_path.replace(output_path)
    except Exception:
        try:
            temporary_path.unlink(missing_ok=True)
        except OSError:
            pass
        raise


class KernelLeak:

    def __init__(self):
        self.process_name = ''
        self.happen_time = ''
        self.reason = ''
        self.warnings: List[str] = []
        self._reset_parsers()

    def __str__(self):
        return self.format_report()

    @staticmethod
    def normalize_reason(leak_type: str) -> str:
        normalized = leak_type.strip().lower().replace(' ', '_')
        return REASON_ALIASES.get(normalized, normalized)

    @staticmethod
    def log_split(context: List[str]):
        generated_indexes = [
            index for index, line in enumerate(context)
            if 'Generated by HiviewDFX @OpenHarmony' in line
        ]
        return context[generated_indexes[-1]:] if generated_indexes else context

    @staticmethod
    def _visible_markers(context: List[str]):
        markers = []
        for line in context:
            stripped = line.strip().lstrip('\ufeff')
            if (stripped.startswith('LOGGER_') or stripped.startswith('MM_') or
                    'memoryName' in stripped or 'dma_heap info' in stripped):
                markers.append(stripped[:120])
            if len(markers) >= 8:
                break
        return markers

    @classmethod
    def leak_type_build(cls, context: List[str]):
        memory_name_pattern = re.compile(r'memoryName\s*:\s*(?P<leak_type>[^\s,*]+)', re.IGNORECASE)
        for line in context:
            match = memory_name_pattern.search(line.lstrip('\ufeff'))
            if match:
                return cls.normalize_reason(match.group('leak_type'))

        stripped_lines = {line.strip().lstrip('\ufeff') for line in context}
        if stripped_lines & DMA_MARKERS:
            return KernelMemoryReason.ION.value
        if any('Process dma_heap info' in line for line in context):
            return KernelMemoryReason.ION.value
        if any(re.search(r'^\s*Process\s+pid\s+fd\s+size_bytes\s+ino(?:\s|$)', line,
                         re.IGNORECASE) for line in context):
            return KernelMemoryReason.ION.value
        return ''

    def build(self, log_path: str):
        target_context = self._load_context(log_path)
        self.reason = self.leak_type_build(target_context)
        builder = self._resolve_builder()
        if not builder:
            markers = self._visible_markers(target_context)
            marker_text = ', '.join(markers) if markers else '未发现结构标记'
            raise ValueError(f'不支持或无法识别kernel日志格式；检测到: {marker_text}')
        builder(deepcopy(target_context))
        handler_errors = self._handler_errors()
        if handler_errors:
            raise ValueError(f'kernel日志解析失败: {"; ".join(handler_errors)}')
        if self.reason == KernelMemoryReason.ION.value:
            self._validate_dma_result()
        self.warnings = list(dict.fromkeys(self.warnings))
        return self

    def ashmem_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.ASHMEM.value
        self.kernel_header.next_handle(self.mem_check_proc_info)
        self.kernel_header.handle(context)

    def ion_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.ION.value
        self.kernel_header \
            .next_handle(self.mem_check_meminfo) \
            .next_handle(self.mem_check_proc_info) \
            .next_handle(self.mem_check_dma_buf_info)
        self.kernel_header.handle(context)

    def gpu_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.GPU.value
        self.kernel_header.next_handle(self.mem_check_proc_info)
        self.kernel_header.handle(context)

    def slab_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.SLAB.value
        self.kernel_header.next_handle(self.mem_check_proc_info)
        self.kernel_header.handle(context)

    def kernel_zone_build(self, context: List[str]):
        self.kernel_header.next_handle(self.mem_check_smaps_info)
        self.kernel_header.handle(context)

    def to_dict(self, top_n: int = 5) -> Dict[str, object]:
        result = {
            'process_name': self.process_name,
            'happen_time': self.happen_time,
            'reason': self.reason,
            'warnings': self.warnings,
        }
        if self.reason == KernelMemoryReason.ION.value:
            result['dma'] = self._dma_summary(top_n)
        return result

    def format_report(self, top_n: int = 5) -> str:
        display_reason = 'ion (DMA)' if self.reason == KernelMemoryReason.ION.value else self.reason
        lines = [
            f'泄露类型：{display_reason}',
            f'时间：{self.happen_time}',
            f'进程：{self.process_name}',
        ]
        if self.reason == KernelMemoryReason.ION.value:
            summary = self._dma_summary(top_n)
            lines.extend(self._format_dma_overview(summary))
            lines.extend(self._format_top_processes(summary['top_processes']))
            lines.extend(self._format_buffer_breakdown(summary['top_process_buffer_breakdown']))
            lines.extend(self._format_field_breakdown(summary, 'buf_type'))
            lines.extend(self._format_field_breakdown(summary, 'leak_type'))
        self._append_warnings(lines)
        return '\n'.join(lines)

    def _reset_parsers(self):
        self.kernel_header: KernelHeader = KernelHeader()
        self.mem_check_proc_info: MemCheckProcInfo = MemCheckProcInfo()
        self.mem_check_dma_buf_info: ProcessDmaBuf = ProcessDmaBuf()
        self.mem_check_detial_info: MemCheckDetialInfo = MemCheckDetialInfo()
        self.mem_check_smaps_info = MemCheckSmapsInfo()
        self.mem_check_meminfo: MemCheckMemInfo = MemCheckMemInfo()

    def _handler_errors(self):
        handlers = [
            self.kernel_header,
            self.mem_check_meminfo,
            self.mem_check_proc_info,
            self.mem_check_dma_buf_info,
            self.mem_check_smaps_info,
        ]
        return [handler.build_error for handler in handlers if handler.is_build_fail]

    def _load_context(self, log_path: str) -> List[str]:
        metadata = parse_kernel_file_name(log_path)
        if not metadata:
            raise ValueError(
                'kernel日志文件名不符合 memleak-kernel-{process}-{pid}-{timestamp}.txt 规范: '
                f'{Path(log_path).name}'
            )
        path = Path(log_path)
        if not path.is_file():
            raise ValueError(f'kernel日志文件不存在: {log_path}')
        self.process_name = str(metadata['process_name'])
        self.happen_time = str(metadata['timestamp'])
        self.reason = ''
        self.warnings = []
        self._reset_parsers()
        context = read_file_to_list(path, warnings=self.warnings)
        if not context:
            raise ValueError('kernel日志为空。')
        return self.log_split(context)

    def _resolve_builder(self):
        builders = {
            KernelMemoryReason.ION.value: self.ion_leak_build,
            KernelMemoryReason.ASHMEM.value: self.ashmem_leak_build,
            KernelMemoryReason.GPU.value: self.gpu_leak_build,
            KernelMemoryReason.SLAB.value: self.slab_leak_build,
            KernelMemoryReason.KERNEL_ZONE.value: self.kernel_zone_build,
        }
        return builders.get(self.reason)

    def _validate_dma_result(self):
        dma_info = self.mem_check_proc_info.dma_heap_info
        if not dma_info.dma_heap_list:
            raise ValueError('已识别为DMA日志，但没有解析到有效DMA数据行。')
        self.warnings.extend(dma_info.warnings)
        self.warnings.extend(self.mem_check_dma_buf_info.warnings)
        unknown_count = sum(
            1 for heap in dma_info.magic_to_dma_heap.values()
            if dma_info._reclaim_state(heap.is_reclaim) == 'unknown'
        )
        if unknown_count:
            self.warnings.append(
                f'{unknown_count}个DMA Buffer未提供有效is_reclaim值，回收状态记为“未知”，'
                '不强行计入DDR或可回收内存。'
            )
        detail_bytes = sum(int(heap.size) for heap in dma_info.magic_to_dma_heap.values())
        reported_bytes = self.mem_check_meminfo.ion_total_use_bytes
        if reported_bytes and detail_bytes != reported_bytes:
            self.warnings.append(
                f'系统MemInfo DMA总量为{reported_bytes} B，可解析明细覆盖{detail_bytes} B，'
                f'差额{reported_bytes - detail_bytes} B。'
            )

    def _format_dma_overview(self, summary: Dict[str, object]) -> List[str]:
        lines = [
            f'DMA记录数：{summary["parsed_rows"]}',
            f'无效DMA记录数：{summary["invalid_rows"]}',
            f'唯一DMA Buffer数：{summary["unique_buffer_count"]}',
            f'DMATotalUsed（系统MemInfo优先，否则按ino明细去重）：{_human_bytes(summary["dma_total_used_bytes"])}',
            f'DMA明细覆盖总量（按ino去重）：{_human_bytes(summary["dma_detail_total_bytes"])}',
            f'原始引用合计（未按ino去重）：{_human_bytes(summary["raw_reference_bytes"])}',
            f'DDR DMA：{_human_bytes(summary["ddr_bytes"])}',
            f'可回收/UFS DMA：{_human_bytes(summary["reclaim_bytes"])}',
            f'回收状态未知DMA：{_human_bytes(summary["reclaim_state_unknown_bytes"])}',
            f'未归属DMA：{_human_bytes(summary["unattributed_bytes"])}',
        ]
        if summary['reported_ion_total_used']:
            unit = summary['reported_ion_total_used_unit'] or '(单位缺失)'
            lines.append(f'日志MemInfo上报IonTotalUsed：{summary["reported_ion_total_used"]} {unit}')
            lines.append(f'系统总量与明细差额：{summary["system_minus_detail_bytes"]} B')
        return lines

    def _format_top_processes(self, processes: List[Dict[str, object]]) -> List[str]:
        if not processes:
            return []
        rows = [
            (
                rank, row['process_name'], row['pid'], _human_bytes(row['total_bytes']),
                _human_bytes(row['private_bytes']), _human_bytes(row['shared_bytes']),
                row['top_buffer_name'],
            )
            for rank, row in enumerate(processes, 1)
        ]
        table = _format_table(
            ('排名', '进程名', 'PID', 'DMA使用', '进程私有', '共享归属', 'Top buf_name'), rows
        )
        return ['\nDMA使用TOP进程：', table]

    def _format_buffer_breakdown(self, breakdown: List[Dict[str, object]]) -> List[str]:
        if not breakdown:
            return []
        rows = [
            (
                row['size_bytes'], _human_bytes(row['used_bytes']), row['count'],
                row['buf_name'], row['buf_type'], row['leak_type'],
            )
            for row in breakdown
        ]
        table = _format_table(
            ('size_bytes', '占用内存', '数量', 'buf_name', 'buf_type', 'leak_type'), rows
        )
        return ['\nTOP1进程size/buffer拆解（Top10）：', table]

    def _format_field_breakdown(self, summary: Dict[str, object], field_name: str) -> List[str]:
        breakdown = summary[f'{field_name}_breakdown']
        if not breakdown:
            return []
        rows = [
            (row[field_name], _human_bytes(row['used_bytes']), row['buffer_count'])
            for row in breakdown
        ]
        table = _format_table((field_name, '占用内存', 'Buffer数'), rows)
        return [f'\nDMA {field_name}聚合（Top10）：', table]

    def _append_warnings(self, lines: List[str]):
        if self.warnings:
            lines.append('\n解析告警：')
            lines.extend(f'- {warning}' for warning in self.warnings)

    def _dma_totals(self, dma_info) -> Dict[str, int]:
        raw_bytes = sum(
            int(getattr(heap, 'raw_size', '') or heap.size) for heap in dma_info.dma_heap_list
        )
        detail_bytes = sum(int(heap.size) for heap in dma_info.magic_to_dma_heap.values())
        reported_bytes = self.mem_check_meminfo.ion_total_use_bytes
        return {
            'raw': raw_bytes,
            'detail': detail_bytes,
            'reported': reported_bytes,
            'unique': reported_bytes or detail_bytes,
            'ddr': sum(dma_info.pid_to_dma_in_ddr.values()),
            'reclaim': sum(dma_info.pid_to_dma_in_ufs.values()),
            'unknown': sum(dma_info.pid_to_dma_unknown.values()),
        }

    def _build_process_rows(self, dma_info, top_n: int):
        rows = []
        for pid in set(dma_info.pid_owned_magic_dict):
            ddr = dma_info.pid_to_dma_in_ddr.get(pid, 0)
            reclaim = dma_info.pid_to_dma_in_ufs.get(pid, 0)
            unknown = dma_info.pid_to_dma_unknown.get(pid, 0)
            buffer_totals = defaultdict(int)
            for magic, heap in dma_info.pid_owned_magic_dict[pid].items():
                buffer_totals[heap.buf_name or 'NULL'] += dma_info.pid_owned_magic_size[pid][magic]
            top_name = max(buffer_totals.items(), key=lambda item: item[1])[0] if buffer_totals else 'NULL'
            rows.append({
                'process_name': dma_info.pid_names.get(pid, ''), 'pid': pid,
                'ddr_bytes': ddr, 'reclaim_bytes': reclaim,
                'reclaim_state_unknown_bytes': unknown,
                'private_bytes': dma_info.pid_to_dma_private.get(pid, 0),
                'shared_bytes': dma_info.pid_to_dma_shared.get(pid, 0),
                'total_bytes': ddr + reclaim + unknown, 'top_buffer_name': top_name,
            })
        rows.sort(key=lambda row: (-row['total_bytes'], row['process_name'], row['pid']))
        return rows, rows[:top_n]

    def _build_buffer_breakdown(self, dma_info, top_processes):
        if not top_processes:
            return []
        top_pid = top_processes[0]['pid']
        grouped = defaultdict(lambda: {'count': 0, 'used_bytes': 0})
        for magic, heap in dma_info.pid_owned_magic_dict[top_pid].items():
            key = (int(heap.size), heap.buf_name or 'NULL', heap.buf_type or 'NULL', heap.leak_type or 'NULL')
            grouped[key]['count'] += 1
            grouped[key]['used_bytes'] += dma_info.pid_owned_magic_size[top_pid][magic]
        rows = []
        for key, values in grouped.items():
            size_bytes, buf_name, buf_type, leak_type = key
            rows.append({
                'size_bytes': size_bytes, 'used_bytes': values['used_bytes'],
                'count': values['count'], 'buf_name': buf_name,
                'buf_type': buf_type, 'leak_type': leak_type,
            })
        rows.sort(key=lambda row: (-row['used_bytes'], -row['size_bytes'], row['buf_name']))
        return rows[:10]

    def _aggregate_unique_field(self, dma_info, field_name: str):
        aggregated = defaultdict(lambda: {'buffer_count': 0, 'used_bytes': 0})
        for heap in dma_info.magic_to_dma_heap.values():
            value = getattr(heap, field_name, '') or 'NULL'
            aggregated[value]['buffer_count'] += 1
            aggregated[value]['used_bytes'] += int(heap.size)
        rows = [
            {field_name: value, **counters} for value, counters in aggregated.items()
        ]
        rows.sort(key=lambda row: (-row['used_bytes'], -row['buffer_count'], row[field_name]))
        return rows[:10]

    def _dma_summary(self, top_n: int = 5) -> Dict[str, object]:
        dma_info = self.mem_check_proc_info.dma_heap_info
        totals = self._dma_totals(dma_info)
        process_rows, top_processes = self._build_process_rows(dma_info, top_n)
        attributed = sum(row['total_bytes'] for row in process_rows)
        detail_unattributed = max(0, totals['detail'] - attributed)
        system_uncovered = max(0, totals['unique'] - totals['detail'])
        return {
            'parsed_rows': len(dma_info.dma_heap_list),
            'invalid_rows': dma_info.invalid_row_count,
            'unique_buffer_count': len(dma_info.magic_to_dma_heap),
            'raw_reference_bytes': totals['raw'],
            'dma_total_used_bytes': totals['unique'],
            'dma_detail_total_bytes': totals['detail'],
            'system_uncovered_bytes': system_uncovered,
            'system_minus_detail_bytes': totals['reported'] - totals['detail'] if totals['reported'] else 0,
            'ddr_bytes': totals['ddr'], 'reclaim_bytes': totals['reclaim'],
            'reclaim_state_unknown_bytes': totals['unknown'],
            'detail_unattributed_bytes': detail_unattributed,
            'unattributed_bytes': detail_unattributed + system_uncovered,
            'reported_ion_total_used': self.mem_check_meminfo.ion_total_use,
            'reported_ion_total_used_unit': self.mem_check_meminfo.ion_total_use_unit,
            'reported_ion_total_used_bytes': totals['reported'],
            'top_processes': top_processes,
            'top_process_buffer_breakdown': self._build_buffer_breakdown(dma_info, top_processes),
            'buf_type_breakdown': self._aggregate_unique_field(dma_info, 'buf_type'),
            'leak_type_breakdown': self._aggregate_unique_field(dma_info, 'leak_type'),
        }


def main() -> int:
    parser = argparse.ArgumentParser(description='解析kernel侧内存泄漏日志')
    parser.add_argument('-p', '--path', required=True, help='kernel日志文件路径')
    parser.add_argument('--json', action='store_true', help='输出结构化JSON')
    parser.add_argument('--no-pickle', action='store_true', help='不生成兼容用pkl文件')
    parser.add_argument('--top', type=int, default=5, help='输出Top进程数量，默认5')
    args = parser.parse_args()
    if args.top <= 0:
        parser.error('--top 必须大于0')

    try:
        kernel_leak = KernelLeak().build(args.path)
    except (OSError, ValueError) as error:
        print(f'解析失败：{error}', file=sys.stderr)
        return 2

    if not args.no_pickle:
        kernel_leak_path = Path(args.path).with_suffix('.pkl')
        try:
            write_pickle_atomic(kernel_leak, kernel_leak_path)
        except Exception as error:
            print(f'pkl写入失败：{type(error).__name__}: {error}', file=sys.stderr)
            return 2

    if args.json:
        print(json.dumps(kernel_leak.to_dict(args.top), ensure_ascii=False, indent=2))
    else:
        print(kernel_leak.format_report(args.top))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
